GET http://localhost:3001/api/orders

###

GET http://localhost:3001/api/orders/60ae37859d015b12e47abc92


###

GET http://localhost:3001/api/user-orders/id

###

POST http://localhost:3001/api/orders
Content-Type: application/json

{
    "cartProducts": [{
        "product": {
            "_id": "60af8370a87bace25c67b696"
        },
        "quantity": 1
    },
    {
        "product": {
            "_id": "60acadc7f067a07653c2a50c"
        },
        "quantity": 1
    }],
    "deliveryMethod": {
        "_id": "60af8370b3363f411db460f5"
    },
    //TODO: Validate?
    //"totalPrice": 299,
    "deliveryInformation": {
        "name": "Malin",
        "email": "malin@stonetwig.se",
        "phone": "0707909054",
        "street": "Street name 2",
        "zipcode": "33333",
        "city": "Gothenburg"
    }
    //TODO: Validate in backend – not changed?
    //"deliveryDay": "2021-05-30",
}

###

PUT http://localhost:3001/api/orders/60b0b177c88b6937676fe957/isShipped
Content-Type: application/json

{
    "isShipped": false
}