GET http://localhost:3001/api/orders

###

GET http://localhost:3001/api/orders/60b4e3a9d0752be39431b3c9


###

POST http://localhost:3001/api/orders
Content-Type: application/json

{
    "cartProducts": [{
        "product": {
            "_id": "60acadc7f067a07653c2a506"
        },
        "quantity": 1
    }],
    "deliveryMethod": {
        "_id": "60acadc70cbf89eb9fbaf5b0"
    },
    "deliveryInformation": {
        "name": "Moa",
        "email": "moa@stonetwig.se",
        "phone": "0707909054",
        "street": "Street name 2",
        "zipcode": "33333",
        "city": "Gothenburg"
    }
}

###

PUT http://localhost:3001/api/orders/60b5f1eadb750af4e1274c32/isShipped
Content-Type: application/json

{
    "isShipped": true
}