GET http://localhost:3001/api/categories

###

POST http://localhost:3001/api/categories
Content-Type: application/json

{
    "name": "New Category"
}

###

PUT http://localhost:3001/api/categories/60b9dba913600ec35407a893
Content-Type: application/json

{
    "name": "Test"
}

###

DELETE http://localhost:3001/api/categories/60acadc77735f4166e42b157