
GET http://localhost:3001/api/users

### 

POST http://localhost:3001/api/users
Content-Type: application/json 

{
    "email": "hallo5@gmail.com", 
    "password": "hej"
}

### 

POST http://localhost:3001/api/login
Content-Type: application/json

{
    "email": "hallo4@gmail.com", 
    "password": "hej"

}

