GET http://localhost:3001/api/products

###

GET http://localhost:3001/api/products/60a79b0ae6374ead67a378aa

###

GET http://localhost:3001/api/products/category/60a79608dddab0a695d05e91

###

POST http://localhost:3001/api/products
Content-Type: application/json

{
    "title": "NEW PRODUCT AGAIN",
    "description": "Lorem ipsum dolor sit amet.",
    "price": 222,
    "imageUrl": "https://github.com/msmalinosterberg/miniprojekt/blob/master/src/assets/prod1.png?raw=true",
    "categories": ["60a79608dddab0a695d05e91"]
}

###

PUT http://localhost:3001/api/products/60a6209e4dbb476ac9a6e3d8
Content-Type: application/json

{
    "title": "EDITED PRODUCT",
    "description": "Lorem ipsum dolor sit amet.",
    "price": 222,
    "imageUrl": "https://github.com/msmalinosterberg/miniprojekt/blob/master/src/assets/prod1.png?raw=true"
}

###

DELETE http://localhost:3001/api/products/60a75f989ddc266e97361c84