GET http://localhost:3001/api/products

###

GET http://localhost:3001/api/products?category=60a8b9b6c4649b239bf4900a&category=60a8b9b6c4649b239bf4900c

###

GET http://localhost:3001/api/products/60acadc7f067a07653c2a507

###

POST http://localhost:3001/api/products
Content-Type: application/json

{
    "title": "A NEW PRODUCT 3",
    "description": "Lorem ipsum dolor sit amet.",
    "price": 222,
    "imageUrl": "https://github.com/msmalinosterberg/miniprojekt/blob/master/src/assets/prod1.png?raw=true",
    "categories": ["60a79b0a4bf15893b3aaa098"],
    "inventory": 10
}

###

PUT http://localhost:3001/api/products/60acadc7f067a07653c2a507
Content-Type: application/json

{
    "title": "AN EDITED PRODUCT",
    "description": "Lorem ipsum dolor sit amet.",
    "price": 222,
    "imageUrl": "https://github.com/msmalinosterberg/miniprojekt/blob/master/src/assets/prod1.png?raw=true",
    "inventory": 15
}

###

DELETE http://localhost:3001/api/products/60acadc7f067a07653c2a507